### ISSUE TITLE
Getting no Data on a fresh Discourse installation.

### ISSUE THREAD

**Issue by carstenhag** [davidcelis/new_relic-discourse#5]
http://i.imgur.com/65YuFeQ.png /admin/upgrade says that the repo is up to date.
Followed the Instructions as seen in the README.md.
Excerpt from the app.yml:

```
env:
  LANG: en_US.UTF-8

  STEAM_WEB_API_KEY: '12xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

  NEW_RELIC_LICENSE_KEY: <36b8532042da64exxxxxxxxxxxxxxxxxxxxxxx>
  NEW_RELIC_APP_NAME: <disc-moter8pw>
```

[..]

```
hooks:
  after_code:
    - exec:
        cd: $home/plugins
        cmd:
          - mkdir -p plugins
          - git clone https://github.com/discourse/docker_manager.git
          - git clone https://github.com/defaye/discourse-steam-login.git
          - git clone https://github.com/davidcelis/new_relic-discourse.git
```

Ran the rebuild too. What could be the issue here?
